In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df= pd.read_csv("Used_Car_Dataset.csv")
df

Year  Mileage_km  Engine_Size_cc  Num_Owners  Fuel_Efficiency_kmpl  \
0    2014      127989            3062           3             16.249345   
1    2017      281393            4029           2             17.237899   
2    2001      249255            2916           3             13.180936   
3    2009      115361            1192           4             11.090744   
4    2022      291744            1908           4              9.460477   
..    ...         ...             ...         ...                   ...   
995  2019      149258            3368           1             14.459319   
996  2011      223827            2685           4             15.624249   
997  2015      272201            2099           1             24.671020   
998  2009      154805            3138           1             13.954630   
999  2009      286301            1876           3             15.687110   

        Price_INR  
0    1.636551e+06  
1    2.206040e+06  
2    2.615662e+05  
3    1.660000e+05  
4    1.660000e+05  
..            ...  
995  2.000275e+06  
996  5.127141e+05  
997  4.025865e+05  
998  1.898584e+06  
999  1.660000e+05  

[1000 rows x 6 columns]

In [4]:
df.isnull()

Year  Mileage_km  Engine_Size_cc  Num_Owners  Fuel_Efficiency_kmpl  \
0    False       False           False       False                 False   
1    False       False           False       False                 False   
2    False       False           False       False                 False   
3    False       False           False       False                 False   
4    False       False           False       False                 False   
..     ...         ...             ...         ...                   ...   
995  False       False           False       False                 False   
996  False       False           False       False                 False   
997  False       False           False       False                 False   
998  False       False           False       False                 False   
999  False       False           False       False                 False   

     Price_INR  
0        False  
1        False  
2        False  
3        False  
4        False  
..         ...  
995      False  
996      False  
997      False  
998      False  
999      False  

[1000 rows x 6 columns]

In [5]:
df.isnull().sum()

Year                    0
Mileage_km              0
Engine_Size_cc          0
Num_Owners              0
Fuel_Efficiency_kmpl    0
Price_INR               0
dtype: int64

In [6]:
reg=linear_model.LinearRegression()
reg.fit(df[['Year','Mileage_km','Engine_Size_cc','Num_Owners','Fuel_Efficiency_kmpl']],df.Price_INR)

LinearRegression()

In [7]:
reg.coef_

array([ 3.36492836e+04, -3.52625832e+00,  7.31324701e+02, -6.51016205e+04,
        1.28843904e+04])

In [8]:
reg.intercept_

-67955295.50835352

In [9]:
reg.predict([[2017,281393,4029,2,17.237899]])

C:\Users\Me\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1961448.84507799])

In [10]:
reg.predict([[2009,115361,1192,4,11.090744]])

C:\Users\Me\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-6447.46487066])

In [11]:
reg.predict([[2009,286301,1876,3,15.687110]])	

C:\Users\Me\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([15323.02792928])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Year                  1000 non-null   int64  
 1   Mileage_km            1000 non-null   int64  
 2   Engine_Size_cc        1000 non-null   int64  
 3   Num_Owners            1000 non-null   int64  
 4   Fuel_Efficiency_kmpl  1000 non-null   float64
 5   Price_INR             1000 non-null   float64
dtypes: float64(2), int64(4)
memory usage: 47.0 KB


In [13]:
x=df[['Year','Mileage_km','Engine_Size_cc','Num_Owners','Fuel_Efficiency_kmpl']]
y=df['Price_INR']

In [14]:
x

Year  Mileage_km  Engine_Size_cc  Num_Owners  Fuel_Efficiency_kmpl
0    2014      127989            3062           3             16.249345
1    2017      281393            4029           2             17.237899
2    2001      249255            2916           3             13.180936
3    2009      115361            1192           4             11.090744
4    2022      291744            1908           4              9.460477
..    ...         ...             ...         ...                   ...
995  2019      149258            3368           1             14.459319
996  2011      223827            2685           4             15.624249
997  2015      272201            2099           1             24.671020
998  2009      154805            3138           1             13.954630
999  2009      286301            1876           3             15.687110

[1000 rows x 5 columns]

In [15]:
y

0      1.636551e+06
1      2.206040e+06
2      2.615662e+05
3      1.660000e+05
4      1.660000e+05
           ...     
995    2.000275e+06
996    5.127141e+05
997    4.025865e+05
998    1.898584e+06
999    1.660000e+05
Name: Price_INR, Length: 1000, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [18]:
len(x_train)

800

In [19]:
len(x_test)

200

In [23]:
x_train

Year  Mileage_km  Engine_Size_cc  Num_Owners  Fuel_Efficiency_kmpl
188  2015      197718            2526           4             17.863885
194  2004       60501            1094           2             13.719656
225  2019       35270            3494           4              8.406031
580  2007        8052            4323           1              9.985670
428  2020       85674            1814           2              9.143091
..    ...         ...             ...         ...                   ...
320  2007      183446            1537           2              9.488768
527  2005      182577            2241           2             18.897103
996  2011      223827            2685           4             15.624249
125  2007       24403            3310           2             14.692592
265  2008       32307            3878           4              8.908388

[800 rows x 5 columns]

In [24]:
from sklearn.linear_model import LinearRegression
clf=LinearRegression()

In [25]:
clf.fit(x_train,y_train)

LinearRegression()

In [26]:
clf.score(x_test,y_test)

0.9405455880113204